### ISSUE TITLE
Bug on demo website

### ISSUE THREAD

**Issue by josephvoxone** [ajithjojo/gmax-crm#2]
![image](https://user-images.githubusercontent.com/26720255/210159607-57fb3966-a5fd-4b75-9098-88c3492abb93.png)
I think your demo got a problem.

**Comment by ajithjojo** [comment]
fixed

**Comment by josephvoxone** [comment]
I think the credentials is invalid.
![image](https://user-images.githubusercontent.com/26720255/210162662-76456640-0996-4ebc-b11c-727cf3ad27f8.png)
Demo Link https://gmax.codeconia.com/ Username : [admin@admin.com](mailto:admin@admin.com)
Passoword : 123456

**Comment by ajithjojo** [comment]
yes fixed. somebody deleted the user account. i added the user again and remove delete account option from demo

**Comment by josephvoxone** [comment]
thanks, appreciate :)

**Comment by josephvoxone** [comment]
now got the new error on your demo site.  @ajithjojo 
![image](https://user-images.githubusercontent.com/26720255/211015090-84adb053-b8a9-481b-8b32-e6f4b55317f5.png)
